<?xml version="1.0"?>
<package format="3">
  <name>opennav_benchmark_mission_dispatcher</name>
  <version>0.1.0</version>
  <description>OpenNav Benchmark Application: maps, annotations, and autonomy scripts</description>
  <maintainer email="steve@opennav.org">Steve Macenski</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>opennav_benchmark_nav2</exec_depend>
  <exec_depend>opennav_benchmark_vlm</exec_depend>
  <exec_depend>nav2_simple_commander</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
